# Generated by Selenium IDE
"""
从seleniumIde 录制中导入到项目中来
-- 不提倡这种录制方式，无效代码比较多
"""
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_seleniumbaiduTest(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1539, 824)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("selenium")
    self.driver.find_element(By.CSS_SELECTOR, ".bdsug-s > b").click()
    element = self.driver.find_element(By.LINK_TEXT, "资讯")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Selenium(WEB自动化工具) - 百度百科").click()
    self.vars["win5931"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win5931"])
    self.driver.execute_script("window.scrollTo(0,2015.199951171875)")
    element = self.driver.find_element(By.ID, "query")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "query")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "query")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").send_keys("Selenium自动化")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Selenium(WEB自动化工具) - 百度百科").click()
    self.vars["win596"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win596"])
